changelog_type: 'pull_request'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: false
include_unlabeled_changes: true
unlabeled_group_title: 'Unlabeled Changes'
pull_request_title_regex: '^update changelog|prepare changelog'
version_regex: '.*'
exclude_labels:
  - bot
  - dependabot
  - dependencies
  - ci
  - documentation
  - dev/ops
  - proposal
group_config:
  - title: Fixed
    labels:
      - bug