workflows:
  openlineage-java:
    jobs:
      - build-client-java:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          context: << pipeline.parameters.build-context >>
      - compile-integration-sql-java-linux:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          matrix:
            alias: compile-integration-sql-java-linux-x86
            parameters:
              image: [
                "quay.io/pypa/manylinux2014_x86_64",
              ]
              resource_class: [ "medium" ]
      - compile-integration-sql-java-linux:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          matrix:
            alias: compile-integration-sql-java-linux-arm
            parameters:
              image: [
                "quay.io/pypa/manylinux2014_aarch64",
              ]
              resource_class: [ "arm.medium" ]
      - compile-integration-sql-java-macos:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
      - build-integration-sql-java:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          context: << pipeline.parameters.build-context >>
          requires:
            - compile-integration-sql-java-linux-arm
            - compile-integration-sql-java-linux-x86
            - compile-integration-sql-java-macos
      - publish-javadoc:
          filters:
            branches:
              only: main
          context: release
      - release-client-java:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              only: main
          context: release
          requires:
            - build-integration-sql-java
            - build-client-java
      - release-integration-sql-java:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              only: main
          context: release
          requires:
            - compile-integration-sql-java-linux-arm
            - compile-integration-sql-java-linux-x86
            - compile-integration-sql-java-macos
      - workflow_complete:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - publish-javadoc
            - release-client-java
            - release-integration-sql-java