workflows:
  openlineage-go:
    jobs:
      - build-client-go:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          context: << pipeline.parameters.build-context >>
      - release-client-go:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              only: main
          context: release
          requires:
            - build-client-go
      - workflow_complete:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - release-client-go
