workflows:
  openlineage-python:
    when:
      matches:
        pattern: '^pull\/[0-9]+$'
        value: << pipeline.git.branch >>
    jobs:
      - build-integration-sql-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          name: "build-integration-sql-python-x86"
          image: "quay.io/pypa/manylinux2014_x86_64"
          resource_class: "medium"
          run_tests: true
      - build-integration-sql-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          name: "build-integration-sql-python-arm"
          image: "quay.io/pypa/manylinux2014_aarch64"
          resource_class: "arm.medium"
          run_tests: true
      - build-integration-sql-python-macos:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
      - unit-test-integration-common:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - build-integration-sql-python-x86
            - build-integration-sql-python-arm
            - build-integration-sql-python-macos
      - build-integration-common:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - unit-test-integration-common
      - unit-test-client-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          name: "CPython 3.9"
          tox_env: py39
          py_env: "3.9"
      - unit-test-client-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          name: "CPython 3.10"
          tox_env: py310
          py_env: "3.10"
      - unit-test-client-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          name: "CPython 3.11"
          tox_env: py311
          py_env: "3.11"
      - unit-test-client-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          name: "CPython 3.12"
          tox_env: py312
          py_env: "3.12"
      - unit-test-client-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          name: "CPython 3.13"
          tox_env: py313
          py_env: "3.13"
      - unit-tests-client-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - "CPython 3.9"
            - "CPython 3.10"
            - "CPython 3.11"
            - "CPython 3.12"
            - "CPython 3.13"
      - build-client-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - unit-tests-client-python
      - build-integration-dbt:
          filters:
            branches:
              only: main
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - integration-test-integration-dbt
      - integration-test-integration-dbt:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - build-client-python
            - build-integration-common
            - build-integration-sql-python-x86
            - build-integration-sql-python-arm
            - build-integration-sql-python-macos
      - workflow_complete:
          requires:
            - build-integration-common
            - build-integration-dbt
      - release-python:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              only: main
          context: release
          requires:
            - build-client-python
            - build-integration-common
            - build-integration-dbt
            - build-integration-sql-python-x86
            - build-integration-sql-python-arm
            - build-integration-sql-python-macos
