workflows:
  openlineage-integration-airflow:
    jobs:
      - build-integration-sql:
          name: build-integration-sql-x86
          image: "quay.io/pypa/manylinux2014_x86_64"
          resource_class: "medium"
      - build-integration-sql:
          name: build-integration-sql-arm
          image: "quay.io/pypa/manylinux2014_aarch64"
          resource_class: "arm.medium"
      - unit-test-integration-common:
          requires:
            - build-integration-sql-x86
          matrix:
            parameters:
              install_parser: [true, false]
      - build-integration-common:
          filters:
            branches:
              only: main
          build_tag: ".dev<< pipeline.number >>"
          requires:
            - unit-test-integration-common
      - unit-test-integration-airflow-1:
          install_parser: true
          requires:
            - build-integration-sql-x86
      - unit-test-integration-airflow-2:
          install_parser: true
          requires:
            - build-integration-sql-x86
      - integration-test-integration-airflow-1-10:
          context: integration-tests
          requires:
            - unit-test-integration-airflow-1
            - unit-test-integration-common
            - unit-test-client-python
            - build-integration-sql-x86
          filters:
            branches:
              ignore: /pull\/[0-9]+/
      - integration-test-integration-airflow:
          matrix:
            parameters:
              airflow-image: [
                'apache/airflow:2.1.4-python3.7',
                'apache/airflow:2.2.4-python3.7',
                'apache/airflow:2.3.0b1-python3.7'
              ]
          context: integration-tests
          requires:
            - unit-test-integration-airflow-2
            - unit-test-integration-common
            - unit-test-client-python
            - build-integration-sql-x86
          filters:
            branches:
              ignore: /pull\/[0-9]+/
      - integration-test-integration-airflow-failure:
          context: integration-tests
          airflow-image: 'apache/airflow:2.2.4-python3.7'
          requires:
            - unit-test-integration-airflow-2
            - unit-test-integration-common
            - unit-test-client-python
            - build-integration-sql-x86
          filters:
            branches:
              ignore: /pull\/[0-9]+/
      - build-integration-airflow:
          filters:
            branches:
              only: main
          build_tag: ".dev<< pipeline.number >>"
          requires:
            - integration-test-integration-airflow
      - workflow_complete:
          requires:
            - build-integration-airflow
            - integration-test-integration-airflow
            - integration-test-integration-airflow-1-10
