workflows:
  openlineage-java:
    jobs:
      - build-client-java
      - build-integration-flink
          matrix:
            parameters:
              flink-version: [ '1.14.4-scala_2.12-java11', '1.15.1-scala_2.12-java11' ]
      - integration-test-integration-flink:
          matrix:
            parameters:
              flink-version: [ '1.14.4-scala_2.12-java11', '1.15.1-scala_2.12-java11' ]
          requires:
            - build-integration-flink
      - publish-snapshot-client-java:
          filters:
            branches:
              only: main
          context: release
          requires:
            - build-client-java
      - build-integration-spark:
          matrix:
            parameters:
              spark-version: [ '2.4.6', '3.1.3', '3.2.2', '3.3.0' ]
      - integration-test-integration-spark:
          matrix:
            parameters:
              spark-version: [ '2.4.6', '3.1.3', '3.2.2', '3.3.0' ]
          requires:
            - build-integration-spark
      - publish-snapshot-integration-spark:
          filters:
            branches:
              only: main
          context: release
          requires:
            - integration-test-integration-spark
      - workflow_complete:
          requires:
            - publish-snapshot-integration-spark
            - integration-test-integration-spark
            - integration-test-integration-flink

