workflows:
  openlineage-proxy:
    jobs:
      - build-proxy-backend
      - build-image-proxy-backend
      - workflow_complete:
          requires:
            - build-proxy-backend
            - build-image-proxy-backend