workflows:
  openlineage-spark:
    jobs:
      - build-integration-spark-interfaces:
          requires:
            - build-client-java
      - build-integration-spark-interfaces-scala:
          matrix:
            parameters:
              scala-binary-version: [ '2.12', '2.13' ]
          requires:
            - build-client-java
      - build-integration-spark-scala-2_12:
          matrix:
            parameters:
              spark-version: [ '2.4.8', '3.2.4', '3.3.4', '3.4.2', '3.5.0' ]
          requires:
           - build-integration-sql-java
           - build-client-java
           - build-integration-spark-interfaces-scala
           - build-integration-spark-interfaces
      - build-integration-spark-scala-2_13:
          matrix:
            parameters:
              spark-version: [ '3.2.4', '3.3.4', '3.4.2', '3.5.0' ]
          requires:
           - build-integration-sql-java
           - build-client-java           
           - build-integration-spark-interfaces-scala
           - build-integration-spark-interfaces
      - approval-integration-spark:
          type: approval
          requires:
            - build-integration-spark-scala-2_12
            - build-integration-spark-scala-2_13
      - integration-test-databricks-integration-spark:
          context: integration-tests
          matrix:
            parameters:
              spark-version: [ '3.4.2', '3.5.0' ]
          requires:
            - approval-integration-spark
      - integration-test-integration-spark-scala-2_12:
          context: integration-tests
          matrix:
            parameters:
              spark-version: [ '2.4.8', '3.2.4', '3.3.4', '3.4.2', '3.5.0' ]
          requires:
            - approval-integration-spark
      - integration-test-integration-spark-scala-2_13:
          context: integration-tests
          matrix:
            parameters:
              spark-version: [ '3.2.4', '3.3.4', '3.4.2', '3.5.0' ]
          requires:
            - approval-integration-spark
      - workflow_complete:
          requires:
            - integration-test-integration-spark-scala-2_12
            - integration-test-integration-spark-scala-2_13
