workflows:
  openlineage-flink:
    jobs:
      - test-integration-flink:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          matrix:
            parameters:
              flink-version: [ '1.15.4', '1.16.2', '1.17.1', '1.18.1', '1.19.0' ]
          requires:
            - build-integration-sql-java
            - build-client-java
      - build-integration-flink:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          context: << pipeline.parameters.build-context >>
          requires:
            - build-integration-sql-java
            - build-client-java
      - build-integration-flink-native:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          context: integration-tests
          requires:
            - build-integration-sql-java
            - build-client-java
      - integration-test-integration-flink:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          context: << pipeline.parameters.build-context >>
          matrix:
            parameters:
              flink-version: [ '1.15.4', '1.16.2', '1.17.1', '1.18.1', '1.19.0' ]
          requires:
            - build-integration-flink
      - release-integration-flink:
          context: release
          requires:
            - build-client-java
            - build-integration-sql-java
            - build-integration-flink
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
            branches:
              only: main
      - workflow_complete:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - integration-test-integration-flink
            - release-integration-flink
