workflows:
  openlineage-integration-airflow:
    jobs:
      - unit-test-integration-common
      - build-integration-common:
          filters:
            branches:
              only: main
          build_tag: ".dev<< pipeline.number >>"
          requires:
            - unit-test-integration-common
      - unit-test-integration-airflow-1
      - unit-test-integration-airflow-2
      - integration-test-integration-airflow-1-10:
          context: integration-tests
          requires:
            - unit-test-integration-airflow-1
            - unit-test-integration-common
            - unit-test-client-python
          filters:
            branches:
              ignore: /pull\/[0-9]+/
      - integration-test-integration-airflow:
          matrix:
            parameters:
              airflow-image: [
                'apache/airflow:2.1.3-python3.7',
                'apache/airflow:2.2.4-python3.7',
                'gcr.io/faktoryzacja/apache/airflow-ol:latest'
              ]
          context: integration-tests
          requires:
            - unit-test-integration-airflow-2
            - unit-test-integration-common
            - unit-test-client-python
          filters:
            branches:
              ignore: /pull\/[0-9]+/
      - integration-test-integration-airflow-failure:
          context: integration-tests
          requires:
            - unit-test-integration-airflow-2
            - unit-test-integration-common
            - unit-test-client-python
          filters:
            branches:
              ignore: /pull\/[0-9]+/
      - build-integration-airflow:
          filters:
            branches:
              only: main
          build_tag: ".dev<< pipeline.number >>"
          requires:
            - integration-test-integration-airflow
      - workflow_complete:
          requires:
            - build-integration-airflow
            - integration-test-integration-airflow-failure
            - integration-test-integration-airflow
            - integration-test-integration-airflow-1-10
