workflows:
  openlineage-spark:
    jobs:
      - build-integration-spark:
          matrix:
            parameters:
              spark-version: [ '2.4.6', '3.2.4', '3.3.2', '3.4.1' ]
          requires:
           - build-integration-sql-java
           - build-client-java
      - integration-test-databricks-integration-spark:
          context: integration-tests
          matrix:
            parameters:
              spark-version: [ '3.4.0' ]
          requires:
            - build-integration-spark
      - integration-test-integration-spark:
          context: integration-tests
          matrix:
            parameters:
              spark-version: [ '2.4.6', '3.2.4', '3.3.2', '3.4.1' ]
          requires:
            - build-integration-spark
      - workflow_complete:
          requires:
            - integration-test-integration-spark