on: [push]

name: Datadog Software Composition Analysis

jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    if: github.repository == 'OpenLineage/OpenLineage' && github.actor != 'dependabot[bot]'
    name: Datadog SBOM Generation and Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Check imported libraries are secure and compliant
        id: datadog-software-composition-analysis
        uses: DataDog/datadog-sca-github-action@main
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_service: openlineage
          dd_env: ci
          dd_site: us5.datadoghq.com